import Head from 'next/head'
import Banner from '../components/Banner'
import Header from '../components/Header'
import axios from 'axios';
import SmallCard from '../components/SmallCard';
import { fetcher } from '../Fetcher/Fetcher';
import MediumCard from '../components/MediumCard';
import LargeCard from '../components/LargeCard';
import Footer from '../components/Footer';

function Home({ exploreData,mediumCard }) {
  return (
    <div>
      <Head>
        <title>natnael-opq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner/>
      {/************************************* Main *********************** */}
      <main className="max-w-6xl mx-auto px-4 py-4 py sm:px-10 sm:py-6 " >
        {/************************************* small Card *********************** */}
        <section className="pt-6" >
          <h1 className="text-4xl font-bold text-slate-600 " >Explore Nearby</h1>
          <div className="  grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 " >
            {
              exploreData?.map((card,i)=> <SmallCard key={i} {...card}/> )
            }
          </div>
        </section>
        {/*************************************  Medium Card *********************** */}
        <section className="pt-6" >
          <h1 className="text-4xl font-bold text-slate-600 " >Live Anywhere</h1>
          <div className="flex snap-x  space-x-5 overflow-hidden overflow-x-scroll scrollbar-hide mt-4 " >
            {
              mediumCard?.map((data,i)=> <MediumCard key={i} {...data}/> )
            }
          </div>
        </section>
        {/************************************* Large Card ***********************  */}
        <LargeCard
            img="https://links.papareact.com/4cj"
            title="The Greatest Outdoors"
            description="Wishlists curated by Airbnb"
            btnText="Get Inspire"
        />
      </main>
    </div>
  )
}


export async function  getStaticProps(){
  const exploreData = await fetcher('https://links.papareact.com/pyp');
  const mediumCard  = await fetcher('https://links.papareact.com/zp1');
  return {
    props: {
      exploreData,
      mediumCard,
    }
  }
}

export default Home;